client_config_backend: settings
client_config:
  client_id: 455036337028-dssnjk1mnc44hf4rff39eff3o89cacqd.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: client_secrets.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
